# -*- coding: utf-8 -*-
"""NB - Data Curation 2.1 - Graph Extraction Apartment Level.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/snt-arg/msd/blob/feature%2Fa_graph_extraction/NB%20-%20Data%20Curation%202.1%20-%20Graph%20Extraction%20Apartment%20Level.ipynb

# Apartment-Level Floor Plan Dataset Derived From MSD

In this notebook, we convert MSD into a information-rich and easy-to-work with dataset of apartment-level floor plans.
The notebook contains the following sections:

**(1) Apartment-level graph extraction.**
From the table (.csv) associated with the MSD floor plan dataset, we extract all distinct apartments that can be found in there (i.e., we develop a function that filters all the building elements corresponding to a particular apartment ID).
Each apartment (i.e., list of building elements) is subsequently converted into a richly-attributed graph, where nodes represent rooms and edges their relations.
Node attributes include the room's geometry and function.
Edge attributes include the type of connectivity and the associated geometry (e.g., geometry of the door) if such a geometry exists in the first place.
Graph-level attributes include the floor ID, apartment ID, and the sets of walls and windows (as geometries) that 'built' the apartment.
We have developed some sophisticated plotting functions in which it is remarkably easy to include your own coloring scheme, and which type of elements you want to be visualized (e.g., whether you want to see back walls, windows, doors, or entrances).

**(2) Filtering.**
In here we remove apartments that are too small or too large ($5 \leq N \leq 12 $, $N$ is the number of rooms), that are not connected (i.e., there exist two, or more, subgraphs that do not share any edge between their corresponding sets of nodes).


**(3) Meta-data analysis.**
In this section, we provide some meta-data about the apartment-level floor plan dataset.
These meta-data regards mostly distributions, such as the distribution of the number of rooms (numeric).

## (1) Apartment-level graph extraction

This part explains how to extract the apartment-level graphs from the corresponding dataframe of MSD and, subsequently, how to nicely visualize the layouts and corresponding connectivity from these graphs.

The graph extraction algorithm in this notebook is slightly different from the one in our Github ($\longrightarrow$ [Data Curation Part 2 - Graph Extraction](https://github.com/caspervanengelenburg/msd/blob/main/NB%20-%20Data%20Curation%202%20-%20Graph%20Extraction.ipynb)):
We include more features / attributes to the nodes, edges, and the graph itself (1) and the room categorizations are slightly different (2).
The format of the data stays the same; so, if you already worked with the other graph data, it won't be difficult to modify the code to work with the ones we'll extract here.

### Loading dataframe

Here we load the MSD dataset, which is already cleaned and filtered on residential-ony floor plans. For details, see:

- Our paper $\longrightarrow$ [MSD: A Benchmark Dataset for Floor Plan Generation of Building Complexes
](https://arxiv.org/abs/2407.10121)
- Our GitHub $\longrightarrow$ [Data Curation Part 1 - Cleaning and Filtering](https://github.com/caspervanengelenburg/msd/blob/main/NB%20-%20Data%20Curation%201%20-%20Cleaning%20and%20Filtering.ipynb)

In our case, the CSV that corresponds to the dataset is saved in in our Drive; hence, we mount our Drive first:

Next, we load the CSV as a `geopandas` dataframe:
"""

import pandas as pd
from geopandas import GeoDataFrame as gdf
import matplotlib.pyplot as plt

# Imports dataframe
# DF = gdf(pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/MSD Table/MSD 5.664k (V1).csv'))  # ! change to your directory
from shapely import wkt

DF = gdf(pd.read_csv('data/MSD 5.664k (V1).csv'))  # ! change to your directory

floor_ids = DF.floor_id.unique()
# Checks dataset size
print(f'Number of floors: {DF.floor_id.nunique()}')
DF.head()

import plot as pl

# Plot geom of rooms, separators and openings in the same plot
floor_DF = DF[DF.floor_id == floor_ids[1]]
floor_DF['geom'] = floor_DF['geom'].apply(wkt.loads)  # Convert WKT strings to Shapely geometry objects
floor_DF = floor_DF.set_geometry('geom')

# pl.plot_DF_geometries(floor_DF)

"""To get an idea of the information within the dataframe, let's show the top (`.head`) of it.
Note that many of the columns from the *Swiss Dwellings* dataset ($\longrightarrow$ [Swiss Dwellings](https://zenodo.org/records/7788422)) are removed, to reduce clutter.
"""

DF.head(10)  # By default, head shows 5. Let's do a bit more, say 10.

"""Each element in the dataframe is an architectural element, and has a corresponding geometry (`geom`), which is a represented by polygon.
Each element is located in:

- a particular site (accessed by the column `site_id`);
- a building (`building_id`);
- a floor (`floor_id)`; and
- an apartment (`apartment_id')`.

(We leave `plan_id`, `unit_id`, and `area_id` for what they are now. I.e.: we do not need them here.)

Before we extract the geometries, let's get an idea of the separator, opening, and room types:
"""

# Show types of separators
print(list(DF[DF.entity_type == 'separator'].entity_subtype.unique()))

# Show types of openings
print(list(DF[DF.entity_type == 'opening'].entity_subtype.unique()))

# Show room types
print(list(DF.roomtype.unique()))

"""Note that we will only need the `roomtype` column for all the information that we want as doors, entrance doors, and windows are already included as distinct categories already.

### Extracting geometries

Let's get the geometries associated with the walls and columns (1), doors (2), entrance doors (3), and windows (4).
We will do so for one floor (randomly sampled from the list of floor IDs in `floor_id`)
"""

from shapely import wkt
def get_geometries_from_id(df, floor_id, apartment_id=None, column='roomtype'):
    """Function that extracts all geometries, associated categories, elevations, and heights
    from a particular floor and apartment ID. Outputs a list of geometries (1), a corresponding
    list of categories (2), a list of elevations (3), and a list of heights (4)."""

    # Samples dataframe based on floor and, if asked for, apartment ID
    df_floor = df[df.floor_id == floor_id].reset_index(drop=True)
    if apartment_id is not None:
        df_floor = df_floor[df_floor.apartment_id == apartment_id].reset_index(drop=True)
    else:
        pass
    df_floor.geom = df_floor.geom.apply(wkt.loads)

    # Get geometries, associated categories, elevations, and heights
    geoms, cats, elevations, heights = zip(*df_floor[["geom", column, "elevation", "height"]].values)

    return geoms, cats, elevations, heights

# Gets list of floor IDs and samples one (at 0)
floor_ids = list(DF.floor_id.dropna().unique())
floor_id = floor_ids[1]

# Gets list of apartment IDs within the given floor
apartment_ids = list(DF[DF.floor_id == floor_id].apartment_id.dropna().unique())

# Gets geometries and associated categories
geoms, cats, elevations, heights = get_geometries_from_id(DF, floor_id)

walls = [geom for geom, type in zip(geoms, cats) if type == 'Structure']  # (1) Walls and columns
doors = [geom for geom, type in zip(geoms, cats) if type == 'Door']  # (2) Doors
entrances = [geom for geom, type in zip(geoms, cats) if type == 'Entrance Door']  # (3) Entrance doors
windows = [geom for geom, type in zip(geoms, cats) if type == 'Window']  # (4) Windows

print(f"Number of apartments:\t\t\t{len(apartment_ids)}\n"
        f"Number of structural elements:\t{len(walls)}\n"
        f"Number of doors:\t\t\t\t{len(doors)}\n"
        f"Number of entrances:\t\t\t{len(entrances)}\n"
        f"Number of windows:\t\t\t{len(windows)}")

"""Let's plot the elements in one figure:"""

def plot_polygon(ax, poly, label=None, **kwargs):
    """Plots a polygon by filling it up. Edges of shapes are avoided to show exactly the area that
    the elements occupy."""
    x, y = poly.exterior.xy
    ax.fill(x, y, label=label, **kwargs)
    return

def draw_walls_and_openings(ax, geoms, cats, colors, **kwargs):
    """Draws the walls and openings of a floor layout."""

    # Extracts walls and columns (1), doors (2), entrances (3), and windows (4)
    walls = [geom for geom, type in zip(geoms, cats) if type == 'Structure']  # (1) Walls and columns
    doors = [geom for geom, type in zip(geoms, cats) if type == 'Door']  # (2) Doors
    entrances = [geom for geom, type in zip(geoms, cats) if type == 'Entrance Door']  # (3) Entrance doors
    windows = [geom for geom, type in zip(geoms, cats) if type == 'Window']  # (4) Windows

    # Plot geometries
    # Draws walls first; doors and windows 'overwrite' the walls. (Makes more sense.)
    _ = [plot_polygon(ax, geom, facecolor=colors[0]) for geom in walls]
    _ = [plot_polygon(ax, geom, facecolor=colors[1]) for geom in doors]
    _ = [plot_polygon(ax, geom, facecolor=colors[2]) for geom in entrances]
    _ = [plot_polygon(ax, geom, facecolor=colors[3]) for geom in windows]

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# Set figure and specs
fs = 10
fig, ax = plt.subplots(1, 1, figsize=(fs, fs))
ax.set_aspect('equal')
ax.axis('off')

# Color palette and naming
sep_colors = ["black", "red", "goldenrod", "deepskyblue"]
sep_names = ["Walls and columns", "Doors", "Entrances", "Windows"]

# Plot geometries
draw_walls_and_openings(ax, geoms, cats, sep_colors)

# Create legend (left middle outside)
patches = [mpatches.Patch(color=color, label=label) for color, label in zip(sep_colors, sep_names)]
_ = plt.legend(handles=patches, loc='upper left', bbox_to_anchor=(1, 0.5), fontsize=fs)

"""That looks good.
We can do the same for all individual apartments on this floor.
Remember: for the floor plan above, there are 5 apartments.
"""

# Gets list of floor IDs and samples one (at 0)
floor_ids = list(DF.floor_id.dropna().unique())
floor_id = floor_ids[1]

# Gets list of apartment IDs within the given floor
apartment_ids = list(DF[DF.floor_id == floor_id].apartment_id.dropna().unique())

# Gets geometries and associated categories
geoms, cats, elevations, heights = get_geometries_from_id(DF, floor_id)

# Get geometries and categories for each apartment ID
apartments = []
for apartment_id in apartment_ids:
    geoms, cats, elevations, heights = get_geometries_from_id(DF, floor_id, apartment_id=apartment_id)
    apartments.append([geoms, cats, elevations, heights])

print(len(apartments))

"""Indeed the lenght of `apartments` corresponds with the number of apartments within the overall floor plan.

Let's plot them individually.
We draw them in different subplots.
And using `unary_union` from `shapely` we construct the boundary of the overall floor plan and plot it underneath the apartments in gray.
"""

import numpy as np
from shapely.ops import unary_union

# Get tightest boundary of floor plan
# First: load all geometries that are walls or columns
# Second: Unite all these geometries using the union of them
# Third: Find the polygon within the union that is largest in terms of area (using np.argsort)
# and choose the largest (which is by default put on the end of the sort)
geoms, cats, elevations, heights  = get_geometries_from_id(DF, floor_id)
structure = unary_union([geom for geom, cat in zip(geoms, cats) if cat == 'Structure'])
boundary = structure.geoms[np.argsort([geom.area for geom in structure.geoms])[-1]]

# Check whether the boundary / polygon makes sense
# (When a shapely Polygon object is called, the shape is directly visualized in the output.)
boundary

# Set figure and specs
fs = 10
nc = len(apartments)  # Number of columns
fig, axs = plt.subplots(1, nc, figsize=(fs*nc, fs))
axs = axs.flatten()

# Loop through apartments
for ax, (geoms, cats, elevations, heights) in zip(axs, apartments):

    # Set axis
    ax.set_aspect('equal')
    ax.axis('off')

    # Plot structure of the whole building
    plot_polygon(ax, boundary, facecolor="gray", alpha=0.2)

    # Plot geometries
    draw_walls_and_openings(ax, geoms, cats, sep_colors)

# Create legend (left middle outside)
patches = [mpatches.Patch(color=color, label=label) for color, label in zip(sep_colors, sep_names)]
_ = plt.legend(handles=patches, loc='upper left', bbox_to_anchor=(1, 1), fontsize=fs*2)

"""You can clearly see that the floor plan is cut into the individual apartments out of which it is composed.

In the next couple of code blocks we will show the spaces as well.
"""

room_names = ['Bedroom', 'Livingroom', 'Kitchen', 'Dining', 'Corridor', 'Stairs', 'Storeroom', 'Bathroom', 'Balcony', 'Other']
room_colors = ['#1f77b4',   # bedroom
               '#e6550d',   # living room
               '#fd8d3c',   # kitchen
               '#fdae6b',   # dining
               '#fdd0a2',   # corridor
               '#72246c',   # stairs
               '#5254a3',   # storeroom
               '#6b6ecf',   # bathroom
               '#2ca02c',   # balcony
               '#8c564b']   # other


def draw_rooms(ax, geoms, cats, room_colors, room_names):
    """Draws the rooms of the floor plan layout."""

    # Simultaneously extract geometries and categories
    # And directly plot them int the correct color
    for geom, cat in zip(geoms, cats):
        if cat in room_names:
            plot_polygon(ax, geom, facecolor=room_colors[room_names.index(cat)])

# Set figure and specs
fs = 10
nc = len(apartments)  # Number of columns
fig, axs = plt.subplots(1, nc, figsize=(fs*nc, fs))
axs = axs.flatten()

# Loop through apartments
for ax, (geoms, cats, elevations, heights) in zip(axs, apartments):

    # Set axis
    ax.set_aspect('equal')
    ax.axis('off')

    # Plot structure of the whole building
    plot_polygon(ax, boundary, facecolor="gray", alpha=0.2)

    # Plot geometries
    draw_rooms(ax, geoms, cats, room_colors, room_names)
    draw_walls_and_openings(ax, geoms, cats, sep_colors)

# Create legend (left middle outside)
colors = room_colors + sep_colors
names = room_names + sep_names
patches = [mpatches.Patch(color=color, label=label) for color, label in zip(colors, names)]
_ = plt.legend(handles=patches, loc='upper left', bbox_to_anchor=(1, 1), fontsize=fs*2)

"""### Extracting graphs

Now it is time to extract the graphs.
We do this per individual apartment.
For now, we will not bother about the entrances and the windows, and completely focus on the layout of the apartment as if it would be isolated from the rest of the world.

As mentioned before, the graph extraction algorithm is slightly different from our previous implemention ($\longrightarrow$ [Data Curation Part 2 - Graph Extraction](https://github.com/caspervanengelenburg/msd/blob/main/NB%20-%20Data%20Curation%202%20-%20Graph%20Extraction.ipynb)):
We include more features / attributes to the nodes, edges, and the graph itself (1) and the room categorization is slightly modified (2).
The format of the data stays the same; so, if you already worked with the other graph data, it won't be difficult to modify your code to work with the ones we'll extract here.

Graphs are stored as `nx.Graph()` data structures, which IMHO is one of the easiest-to-work-with graph containers you can find in Python.

The graph extraction algorithm below should be self-explainable from the comments.

One thing to highlight here (which is quite different from our earlier algorithm) is to way to check the connectivity by doors.
The door geometries are temporarily modified by rotating them 90 degrees and making them slightly smaller.
This means that there is more clearly overlap between the rotated door geometry and the two rooms that the door connects.
This makes the algorithm more robust to slightly misplaced doors.

"""

from warnings import catch_warnings
from copy import deepcopy
from itertools import combinations
import torch
import networkx as nx
from shapely.geometry import Polygon
from shapely.affinity import rotate, scale
import graphs as gr
import utils as ut

def rotate_rectangle(rect: Polygon, scale_factor=0.5, angle=90):
    # Compute centroid (center point)
    centroid = rect.centroid

    # Scale the rectangle (relative to the centroid)
    scaled_rect = scale(rect, xfact=scale_factor, yfact=scale_factor, origin=centroid)

    # Rotate the scaled rectangle around its center
    rotated_rect = rotate(scaled_rect, angle, origin=centroid)

    return rotated_rect

def polygon_to_list(polygon: Polygon) -> list:
    """Converts a polygon into a list of coordinates."""
    return list(zip(*polygon.exterior.coords.xy))

def extract_access_graph(geoms, cats, elevations, heights, names, apartment_id, floor_id):
    """Extracts the access graph from a set of apartment."""

    # Defines the graph
    G = nx.Graph()
    partial_G = []

    # Sets the mapping
    mapping_names = {cat: i for i, cat in enumerate(names)}

    # Initializes empty lists for rooms and their categories, doors, and walls
    rooms, room_cats, doors, entrances, walls, windows = [], [], [], [], [], []
    room_z, doors_z, entrances_z, walls_z, windows_z = [], [], [], [], []

    # Loops through the geometries and corresponding categories
    for geom, cat, height in zip(geoms, cats, heights):

        # Add z-coordinate to the geometry
        z_coord = height / 2

        if cat == 'Door':  # Doors
            doors.append(geom)
            doors_z.append(z_coord)
        elif cat == 'Entrance Door':  # Entrances
            doors.append(geom)
            doors_z.append(z_coord)
            entrances.append(geom)
            entrances_z.append(z_coord)
        elif cat in names[:9]:  # Rooms
            rooms.append(geom)
            room_z.append(z_coord)
            room_cats.append(cat)
        elif cat == 'Structure':  # Walls and columns
            walls.append(geom)
            walls_z.append(z_coord)
        elif cat == 'Window':  # Windows
            windows.append(geom)
            windows_z.append(z_coord)
        else:
            continue

    for key, (room, cat, z) in enumerate(zip(rooms, room_cats, room_z)):
        # for each room in the apartment

        # create dict for room, cat, and z
        room_dict = {
            'geom': room,
            'entity_subtype': cat,
            'category': mapping_names[cat],
            'z': z
        }

        # search for intersections with openings
        wall_indexes, door_indexes, window_indexes = ut.find_intersections(room, walls, doors, windows)

        gr.add_room_geometries(room_dict, floor_id, apartment_id, key, G)

        gr.add_other_geometry(doors, windows, walls, door_indexes, window_indexes, wall_indexes, doors_z, windows_z, walls_z, room_dict, floor_id, apartment_id, key, G)

        gr.connect_rooms_by_proximity(G, doors, entrances, windows)

        partial_G.append(G.copy())
    # # Security checks
    # # #Drop empty nodes
    # nodes_without_data = [n for n, attr in G.nodes(data=True) if not attr]
    # G.remove_nodes_from(nodes_without_data)
    # # #Drop isolated nodes
    # isolated_nodes = list(nx.isolates(G))
    # G.remove_nodes_from(isolated_nodes)

    # Graph attributes / features
    G.graph["Floor ID"] = floor_id  # Floor ID
    G.graph["Apt ID"] = apartment_id  # Apartment ID (i.e., name)
    G.graph["Structure"] = walls  # Walls and columns
    G.graph["Windows"] = windows  # Windows
    G.graph["Entrances"] = entrances  # Entrances (doors)

    return G, partial_G

"""Let's load the graphs in a list called `graphs`:"""

from IPython.display import clear_output
#force reimport of graphs
import importlib

import utils as ut
importlib.reload(ut)
import graphs as gr
importlib.reload(gr)

# Import necessary modules
import matplotlib.pyplot as plt
from shapely.geometry import Polygon

# Initialize emtpy list for graphs
graphs = []
partial_graphs = []

# Loop over apartments
for i, ((geoms, cats, elevations, heights), apartment_id) in enumerate(zip(apartments, apartment_ids)):
    clear_output(wait=True)
    print(f"Graphs extracted: {i+1} / {len(apartments)}")
    G, partials = extract_access_graph(geoms, cats, elevations, heights, names, apartment_id, floor_id)
    graphs.append(G)
    partial_graphs.append(partials)

graph = graphs[0]
print(graph)
print("Nodes:")
for node, data in graph.nodes(data=True):
    print(f"{node}: {data}")
print("\nEdges:")
for u, v, data in graph.edges(data=True):
    print(f"{u} -- {v}: {data}")


print("\nEmpty nodes:")
for n, d in G.degree():
    if d == 0:
        print(n)

print("\nNodes w/o neighbors:")
# search type of nodes that don't hava an edge
for graph in graphs:
    for node, data in graph.nodes(data=True):
        if len(list(graph.neighbors(node))) == 0:
            print(f"{node}: {data}")

print("\nNodes with wall_11:")
for graph in graphs:
    for node, data in graph.nodes(data=True):
        if "wall_11" in node:
            print(f"{node}: {data}")

def plot_a_graph(graphs_list, viz_rooms=True, viz_ws=True, viz_openings=False, viz_room_connection=True, viz_normals=False, viz_room_normals=False, viz_walls=True):
    """
    Visualizes geometries, wall segments, and graph edges for multiple apartments in 2D.

    Parameters:
    graphs_list (list of networkx.Graph): List of graphs with nodes ('type', 'center', 'normal') and edges for the apartments.
    viz_normals (bool): If True, plots wall segment normals.
    viz_rooms (bool): If True, displays room polygons.
    viz_ws (bool): If True, displays wall segments.
    viz_openings (bool): If True, displays openings (doors and windows).
    viz_wall_edges (bool): If True, displays edges between wall segments.
    viz_connection_edges (bool): If True, displays edges connecting rooms via openings.
    viz_walls (bool): If True, displays wall nodes and their edges.
    """
    _, ax = plt.subplots(1, 1, figsize=(10, 10))
    legend_added = False  # Flag to ensure the legend is added only once
    normal_added = False  # Flag to ensure the "Normal" label is added only once

    for graphs in graphs_list:
        # Visualize room polygons
        if viz_rooms:
            room_nodes = [n for n, d in graphs.nodes(data=True) if d['type'] == 'room']
            for idx, room_node in enumerate(room_nodes):
                room_data = graphs.nodes[room_node]
                # Plot the polygon
                room_polygon = Polygon(room_data['polygon'])
                x, y = room_polygon.exterior.xy
                ax.plot(x, y, color='black', label='Room polygon' if not legend_added and idx == 0 else "")
                # Draw room centroids
                ax.scatter(room_data['center'][0], room_data['center'][1], color='blue', s=100, label='Room centroid' if not legend_added and idx == 0 else "")

        # Visualize wall nodes and edges
        if viz_walls:
            wall_nodes = [n for n, d in graphs.nodes(data=True) if d['type'] == 'wall']
            for idx, wn in enumerate(wall_nodes):
                wall_data = graphs.nodes[wn]
                # Plot the polygon of the wall
                wall_polygon = Polygon(wall_data['polygon'])
                x, y = wall_polygon.exterior.xy
                ax.plot(x, y, color='purple', linestyle='-', label='Wall polygon' if not legend_added and idx == 0 else "")
                ax.scatter(wall_data['center'][0], wall_data['center'][1], color='purple', s=50, label='Wall centroid' if not legend_added and idx == 0 else "")

            if viz_normals:
                wall_ws = [n for n, d in graphs.nodes(data=True) if d['type'] == 'wall_ws']
                for idx, wn in enumerate(wall_ws):
                    ws_data = graphs.nodes[wn]
                    ax.scatter(ws_data['center'][0], ws_data['center'][1], color='purple', s=20, label='Wall ws' if not legend_added and idx == 0 else "")
                    ax.arrow(ws_data['center'][0], ws_data['center'][1],
                             ws_data['normal'][0], ws_data['normal'][1],
                             head_width=0.1, head_length=0.1, fc='green', ec='green', label='Normal' if not normal_added else "")
                    normal_added = True

            wall_edges = [(u, v) for u, v, d in graphs.edges(data=True) if 'wall' in u or 'wall' in v]
            for idx, edge in enumerate(wall_edges):
                start_node = graphs.nodes[edge[0]]
                end_node = graphs.nodes[edge[1]]
                ax.plot([start_node['center'][0], end_node['center'][0]],
                        [start_node['center'][1], end_node['center'][1]],
                        color='purple', linestyle='--', label='Wall edge' if not legend_added and idx == 0 else "")

        # Visualize openings
        if viz_openings:
            opening_nodes = [n for n, d in graphs.nodes(data=True) if 'door' in d['type'] or 'window' in d['type']]
            for idx, on in enumerate(opening_nodes):
                opening_data = graphs.nodes[on]
                opening_polygon = Polygon(opening_data['polygon'])
                x, y = opening_polygon.exterior.xy
                ax.plot(x, y, color='orange', label='Opening polygon' if not legend_added and idx == 0 else "")
                # Draw opening centroids
                ax.scatter(opening_data['center'][0], opening_data['center'][1], color='orange', s=10, label='Opening centroid' if not legend_added and idx == 0 else "")

            if viz_normals:
                opening_ws = [n for n, d in graphs.nodes(data=True) if d['type'] == 'door_ws' or d['type'] == 'window_ws']
                for idx, wn in enumerate(opening_ws):
                    ws_data = graphs.nodes[wn]
                    ax.scatter(ws_data['center'][0], ws_data['center'][1], color='orange', s=10, label='Opening ws' if not legend_added and idx == 0 else "")
                    ax.arrow(ws_data['center'][0], ws_data['center'][1],
                             ws_data['normal'][0], ws_data['normal'][1],
                             head_width=0.1, head_length=0.1, fc='green', ec='green', label='Normal' if not normal_added else "")
                    normal_added = True

            # Draw opening edges
            open_edges = [(u, v) for u, v, d in graphs.edges(data=True) if 'door' in u or 'window' in v or 'door' in v or 'window' in u]
            for idx, edge in enumerate(open_edges):
                start_node = graphs.nodes[edge[0]]
                end_node = graphs.nodes[edge[1]]
                ax.plot([start_node['center'][0], end_node['center'][0]],
                        [start_node['center'][1], end_node['center'][1]],
                        color='orange', linestyle='--', label='Opening edge' if not legend_added and idx == 0 else "")

        # Visualize ws room
        if viz_ws:
            ws_nodes = [n for n, d in graphs.nodes(data=True) if d['type'] == 'ws']
            for idx, wn in enumerate(ws_nodes):
                ws_data = graphs.nodes[wn]
                ax.scatter(ws_data['center'][0], ws_data['center'][1], color='red', s=20, label='Ws segment' if not legend_added and idx == 0 else "")
                if viz_room_normals:
                    ax.arrow(ws_data['center'][0], ws_data['center'][1],
                             ws_data['normal'][0], ws_data['normal'][1],
                             head_width=0.1, head_length=0.1, fc='green', ec='green', label='Normal' if not normal_added else "")
                    normal_added = True

            ws_edges = [(u, v) for u, v, d in graphs.edges(data=True) if 'ws_same_room' in d['type'] or 'ws_belongs_room' in d['type']]
            for idx, edge in enumerate(ws_edges):
                start_node = graphs.nodes[edge[0]]
                end_node = graphs.nodes[edge[1]]
                ax.plot([start_node['center'][0], end_node['center'][0]],
                    [start_node['center'][1], end_node['center'][1]],
                    color='gray', linestyle='--', label='Ws edge' if not legend_added and idx == 0 else "")

        # Visualize connection edges
        if viz_room_connection:
            connection_edges = [(u, v) for u, v, d in graphs.edges(data=True) if 'connected' in d['type']]
            for idx, edge in enumerate(connection_edges):
                start_node = graphs.nodes[edge[0]]
                end_node = graphs.nodes[edge[1]]
                ax.plot([start_node['center'][0], end_node['center'][0]],
                        [start_node['center'][1], end_node['center'][1]],
                        color='blue', linestyle='-', label='Connection edge' if not legend_added and idx == 0 else "")

        legend_added = True  # Set the flag to True after processing the first graph

    plt.title("Apartment Graph Visualization")
    plt.legend()
    plt.show()

# plot_a_graph([partial_graphs[0][0]], viz_ws=True, viz_openings=False, viz_room_connection=True, viz_room_normals=True, viz_walls=True)
# plot_a_graph([partial_graphs[0][1]], viz_ws=True, viz_openings=False, viz_room_connection=True, viz_room_normals=True, viz_walls=True)
# plot_a_graph([partial_graphs[0][2]], viz_ws=True, viz_openings=False, viz_room_connection=True, viz_room_normals=True, viz_walls=True)
# plot_a_graph([graphs[0]], viz_openings=False, viz_room_connection=True, viz_normals=True, viz_ws=True, viz_walls=True)

# plot_a_graph(graphs, viz_ws=False)

"""Now, we can loop over all floor and extract the apartment graphs from them."""

# Compute number of apartments
N_apartments = 0
for floor_id in floor_ids:
    N_apartments += DF[DF.floor_id == floor_id].apartment_id.dropna().nunique()

print(f"Number of apartments:\t{N_apartments}")

# compute number of partial graphs for each apartment
def get_partial_graph_counts(partial_graphs):
    N_partial_graphs = []
    for partials in partial_graphs:
        count = 0
        for graphs in partials:
            count += 1
        N_partial_graphs.append(count)
    return N_partial_graphs

N_partial_graphs = get_partial_graph_counts(partial_graphs)
print(f"Number of apartments:\t{len(partial_graphs)}")
print(f"Number of partial graphs:\t{N_partial_graphs}")
res = [partial_graphs[4][5]]
# plot_a_graph(res)

"""It takes quite a while to extract all the graphs.
You can also do it for the first 50 floor plans to check the code, like we do in the following block:
"""

import pickle

def save_pickle(object, filename):
    """Saves a pickled file."""
    with open(filename, 'wb') as f:
        pickle.dump(object, f)
    f.close()

def load_pickle(filename):
    """
    Loads a pickled file.
    """
    with open(filename, 'rb') as f:
        object = pickle.load(f)
        f.close()
    return object

import utils as ut
importlib.reload(ut)
import graphs as gr
importlib.reload(gr)

graphs = []
partial_graphs = []

for floor_id in floor_ids[:20]:

    # Get apartment IDs within the floor
    apartment_ids = list(DF[DF.floor_id == floor_id].apartment_id.dropna().unique())

    # Loop over the apartments and extract the graphs
    for apartment_id in apartment_ids:
        geoms, cats, elevations, heights = get_geometries_from_id(DF, floor_id, apartment_id=apartment_id)
        G, PG = extract_access_graph(geoms, cats, elevations, heights, names, apartment_id, floor_id)
        graphs.append(G)
        partial_graphs.append(PG)

    clear_output(wait=True)
    print(f"Apartments done: {len(graphs)} / {N_apartments}")

N_partial_graphs = get_partial_graph_counts(partial_graphs)

# plot_a_graph([graphs[12]], viz_ws=False,viz_openings=True)
# plot_a_graph([graphs[16]], viz_ws=False,viz_openings=True)

# Saves graphs
# save_pickle(graphs, '/content/drive/MyDrive/Colab Notebooks/Data/MSD Dump/MSD - Some Apartment-Level Graphs.pickle')
save_pickle(partial_graphs, 'data/MSD - Some Apartment-Level partials.pickle')
save_pickle(N_partial_graphs, 'data/MSD - Some Apartment-Level partials counter.pickle')

# Loads graphs
partial_graphs = load_pickle('data/MSD - Some Apartment-Level partials.pickle')
N_partial_graphs = load_pickle('data/MSD - Some Apartment-Level partials counter.pickle')

print(len(partial_graphs))
print(len(N_partial_graphs))
print(N_partial_graphs)
print(partial_graphs[7][7])

"""## (2) Filtering

This section is about removing apartment layouts that are either nearly similar to others (1) are not very informative (e.g., the upper part of an apartment that might only have 1 bedroom) (2).
Why (1)? Too many very similar layouts will slow down and likely bias training.
Why (2)? Good question ...

### Counting storeys in an apartment

Some apartments live at multiple storeys in a building.

Let's plot the histogram of the number of storeys apartments have.
This is easily extracted from the dataframe by counting the number of unique floor IDs can be found when the dataframe is filtered on a particular apartment ID.
"""

# Get apartment IDs
apartment_ids = list(DF.apartment_id.dropna().unique())
print(len(apartment_ids))

# Get unit IDs (Should be more!)
unit_ids = list(DF.unit_id.dropna().unique())
print(len(unit_ids))

# Get storeys per apartment dataframe
storeys_per_apartment = DF.groupby('apartment_id')['floor_id'].nunique()

# Set figure
fs = 7
fig, ax = plt.subplots(1, 1, figsize=(fs, fs))

# Histogram
ax.hist(storeys_per_apartment, bins=range(1, storeys_per_apartment.max() + 2), color='black', align='left', log=True, rwidth=0.9)

# Set labels
ax.set_xlabel('Number of Storeys', fontsize=fs*2)
ax.set_ylabel('Number of Apartments', fontsize=fs*2)
_ = ax.set_title('Storeys per Apartment', fontsize=fs*3)

# Set axes
ax.grid(axis='y', linestyle='--', alpha=1)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

"""Since there are only a few apartments covering multiple storeys, we simply don't consider these apartments."""

single_apartment_ids = storeys_per_apartment[storeys_per_apartment == 1].index.tolist()
print(len(single_apartment_ids))

"""### Extracting all single-storey apartment graphs

In the next cell, we will convert all the (single-storey) apartments to information-rich graphs and put them together in a list.
This procedure takes quite some time (~30 min, depending on your machine / server).
Make sure to save it afterwards: Loading the list of graphs from your folder takes way less time than repeating the extraction.
"""

graphs = []
partial_graphs = []

for floor_id in floor_ids:

    # Get apartment IDs within the floor
    apartment_ids = list(DF[DF.floor_id == floor_id].apartment_id.dropna().unique())
    # Remove those that are covering more than 1 storey (by set intersection)
    apartment_ids = list(set(apartment_ids).intersection(set(single_apartment_ids)))

    # Loop over the apartments and extract the graphs
    for apartment_id in apartment_ids:
        geoms, cats, elevations, heights = get_geometries_from_id(DF, floor_id, apartment_id=apartment_id)
        G, PG = extract_access_graph(geoms, cats, elevations, heights, names, apartment_id, floor_id)
        graphs.append(G)
        partial_graphs.append(PG)

    clear_output(wait=True)
    print(f"Apartments done: {len(graphs)} / {N_apartments}")
    if len(graphs) >= 5000:
        break

N_partial_graphs = get_partial_graph_counts(partial_graphs)

"""Again: don't forget to save them.
Note that it's about 150MB only!
"""

# Saves graphs
save_pickle(partial_graphs, f'data/MSD - Apartment-Level partials graphs {len(partial_graphs)/1000:.1f}K.pickle')
save_pickle(N_partial_graphs, 'data/MSD - Apartment-Level partials graphs counter.pickle')

"""Let's visualize a couple of them:"""

import random

random.seed(42)
# sample randomly 2% of the graphs as indexes
sample_size = int(len(N_partial_graphs) * 0.1)
sample_indexes = random.sample(range(len(N_partial_graphs)), sample_size)
print("Sampled index:", sample_indexes)
for i in sample_indexes:
    graph_length = N_partial_graphs[i] - 1
    graph_list = [partial_graphs[i][graph_length]]
    # plot_a_graph(graph_list, viz_openings=True)

"""While many of the floor plans are great, there are many that are not really informative, such as:

- Floor plans that consist of a few number of rooms (some are only bedrooms ...)
- Floor plans without a living room. Reconsidered: We keep them in, there are many apartments without it.

Let's check the sizes (in terms of amount of rooms) of the apartments (1) and number of apartments with a living room more closely (2).
"""

from tqdm.auto import tqdm

N_rooms = []
N_with_living = 0

for G in tqdm(graphs):
    N_rooms.append(sum(1 for _, data in G.nodes(data=True) if data["type"] == "room"))  # (1)
    # Checks presence of living room among the nodes
    N_with_living += 1 if 1 not in [d for _, d in G.nodes(data="category")] else 0  # (2)

# Print number of apartments that have a living room
print(N_with_living)
print(N_rooms[:50])

"""Check distribution of the apartment sizes (i.e., the amount of rooms) through a histogram."""

# Set figure
fs = 7
fig, ax = plt.subplots(1, 1, figsize=(fs, fs))

# Histogram
ax.hist(N_rooms, bins=range(1, np.max(N_rooms) + 2), color='black', align='left', rwidth=0.7)

# Set labels
ax.set_xlabel('Number of Spaces', fontsize=fs*2)
ax.set_ylabel('Number of Apartments', fontsize=fs*2)
_ = ax.set_title('Number of Spaces per Apartment', fontsize=fs*3)

# Set axes
ax.grid(axis='y', linestyle='--', alpha=1)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

"""We keep all apartments that have between 5 and 12 rooms."""

# graphs_subset = []
# partials_graphs_subset = []
# graphs_dim = []
#be carefull if you decomment, check loop in next cell
# for i, graph in enumerate(graphs):
#     # count number of nodes in graph where  data["type"] == "room")
#     N_rooms = sum(1 for _, data in graph.nodes(data=True) if data["type"] == "room")
#     if 5 <= N_rooms <= 12:
#         graphs_subset.append(graph)
#         partials_graphs_subset.append(partial_graphs[i])
#         graphs_dim.append(len(partial_graphs[i]))

# print(f"Number of apartments with 5-12 rooms: {len(graphs_subset)}")

"""Some apartment are not fully connected.
Here, we keep all apartments that are connected.
"""

partials_graphs_subset = []
graphs_dim = []
graph_copy = []

print(f"Number of apartments: {len(graphs)}")

#get room connection graph in the subset
for graph in graphs:
    # Create a subgraph with only nodes of type 'room' and edges with label 'opening'
    nodes_to_keep = [n for n, d in graph.nodes(data=True) if d.get('type') == 'room']
    edges_to_keep = [(u, v) for u, v, d in graph.edges(data=True) if d.get('type') == 'opening']

    # Create a new graph with the filtered nodes and edges
    copy = graph.subgraph(nodes_to_keep).copy()
    copy.add_edges_from(edges_to_keep)

    # Update the graph in the graph_copy list
    graph_copy.append(copy)

assert len(graph_copy) == len(graphs), "The number of graphs in graph_copy should match the number of graphs in graphs."

for i, graph in enumerate(graph_copy):
    if nx.is_connected(graph):
        partials_graphs_subset.append(partial_graphs[i])
        graphs_dim.append(len(partial_graphs[i]))

print(f"Number of apartments connected: {len(partials_graphs_subset)}")

"""So, ultimately, in the final dataset we have 16771 apartment-level floor plan graphs."""

random.seed(42)
# sample randomly 2% of the graphs as indexes
sample_size = int(len(graphs_dim) * 0.1)
sample_indexes = random.sample(range(len(graphs_dim)), sample_size)
print("Sampled index:", sample_indexes)
for i in sample_indexes:
    graph_length = graphs_dim[i] - 1
    graph_list = [partials_graphs_subset[i][graph_length]]
    # plot_a_graph(graph_list, viz_openings=True)

"""Let's save this 'cleaned' dataset as well:"""

# Saves graphs
save_pickle(partials_graphs_subset, f'data/MSD - Apartment-Level partials graphs cleaned {len(partial_graphs)/1000:.1f}K.pickle')
save_pickle(graphs_dim, 'data/MSD - Apartment-Level partials graphs counter cleaned.pickle')